### ISSUE TITLE
Update of indicators seems to work only sometimes

### ISSUE THREAD

**Issue by jschirrmacher** [neustartklima/ich-kann-klima#181] opened 2022-01-20 17:12 UTC
It seems that the three visible indicators are only updated sometimes. My game ended with the information that I ran out of money, but the indicator is still around 50%.

<img width="1181" alt="Bildschirmfoto 2022-01-20 um 18 08 21" src="https://user-images.githubusercontent.com/2821879/150388078-f0a36ac6-497c-43e9-a5d0-3dc931cd37ae.png">

**Comment by jschirrmacher** [comment] 2022-01-20 17:13
My game id was `e89c1c0-7a12-11ec-882f-319e3f653048`

**Comment by mdrie** [comment] 2022-01-20 17:15
Might be duplicate of #180 which I just fixed...

**Comment by jschirrmacher** [comment] 2022-01-20 17:17
At least, I saw this error just a few minutes ago in the production environment. Is your fix already deployed?

**Comment by mdrie** [comment] 2022-01-20 17:23
Minutes ago... Not sure, if you already got it.

**Comment by jschirrmacher** [comment] 2022-01-20 17:43
Hm, I've just tried again after reloading the page, and the effect is still the same. However, popularity changes visibly, and CO2 budget as well, though very smoothly. So, maybe this is related to finances only.

**Comment by mdrie** [comment] 2022-01-20 17:57
Thanks! Will have a look tomorrow. I had my fingers deep in that s...tuff today - should be easy for me.

**Closed** 2022-02-09 19:24 UTC
Labels: bug
